### ISSUE TITLE
How is it install?

### ISSUE THREAD

**Issue by ugurbay** [ganochenkodg/svelte-crud#9]
Thanks for your great job. I am new in programming. I want to install this svelte-crud project on my local computer but there is no full instructions for install with npm. Could you please explain detail installing instructions?

**Comment by zipzit** [comment]
Open up your operating system.  Open up a terminal. `cd` (change directories) to a convenient folder, somewhere you can find again.  I like to start at c:/temp  

`git clone https://github.com/ganochenkodg/svelte-crud.git`
`cd svelte-crud` 
(I'm assuming you have Docker installed on your machine.  Update docker to latest version...)
`docker compose up -d`   (this starts the process... builds all six involved containers...You will see a whole bunch of messages in the terminal console.  )

Note, the  flag:  `-d`, `--detach`       -->  Detached mode: Run containers in the background,  print new container names.

Finally, point your browser to  `http://localhost:8080`

You will see a book management tool, which allows you to use any one of four different database systems.  Pretty awesome learning tool.   Many thanks to @ganochenkodg for sharing the project.  

Note, you will need to learn some command line instructions for using docker.  It does create a whole lot of files on your computer.  Attached is my personal cheat sheet for Docker commands.  
[Zipzit Docker Cheat Sheet.txt](https://github.com/ganochenkodg/svelte-crud/files/7096049/Zipzit.Docker.Cheat.Sheet.txt)
